import { describe, it, expect } from 'vitest'
import { Buddy } from './buddy'
import { RUN_SPEED, WALK_SPEED } from '../shared/types'

function seq(values: number[]) {
  let i = 0
  return () => values[i++ % values.length] ?? 0
}
// rng consumption order: tick#1 -> wander interval; wander -> target; arrival -> rest kind, rest length

describe('Buddy wander', () => {
  it('does nothing before the first wander time, then moves', () => {
    const b = new Buddy({ rng: seq([0, 0.9]), initialX: 0 })
    b.tick(0)
    b.tick(7999)
    expect(b.view().state.activity).toBe('idle')
    b.tick(8000)
    const v = b.view()
    expect(v.state.activity).toBe('running')
    expect(v.state.targetX).toBeCloseTo(0.9)
    expect(v.state.facing).toBe('right')
    expect(v.animation).toBe('run')
    expect(v.speed).toBe(RUN_SPEED)
  })
  it('walks when the target is near', () => {
    const b = new Buddy({ rng: seq([0, 0.1]), initialX: 0 })
    b.tick(0); b.tick(8000)
    expect(b.view().state.activity).toBe('walking')
    expect(b.view().speed).toBe(WALK_SPEED)
  })
  it('rests on arrival then wanders again', () => {
    const b = new Buddy({ rng: seq([0, 0.9, 0.5, 0, 0, 0.2]), initialX: 0 })
    b.tick(0); b.tick(8000)
    b.arrived()                       // rest kind 0.5 -> sitting, rest 0 -> 5000 ms
    expect(b.view().state.x).toBeCloseTo(0.9)
    expect(b.view().state.activity).toBe('sitting')
    expect(b.view().state.targetX).toBeUndefined()
    b.tick(12999)
    expect(b.view().state.activity).toBe('sitting')
    b.tick(13000)                     // rest over -> idle, next wander at +8000
    expect(b.view().state.activity).toBe('idle')
    b.tick(21000)
    expect(['walking', 'running']).toContain(b.view().state.activity)
  })
  it('does not wander while the panel is open, resumes after close', () => {
    const b = new Buddy({ rng: seq([0]), initialX: 0.5 })
    b.tick(0)
    b.openPanel()
    expect(b.view().state.activity).toBe('projecting')
    b.tick(60000)
    expect(b.view().state.activity).toBe('projecting')
    b.closePanel()
    expect(b.view().state.activity).toBe('idle')
    b.tick(68000)
    expect(['walking', 'running']).toContain(b.view().state.activity)
  })
  it('a wander rest can land on looking; oneShotDone ends it, then a later wander resumes', () => {
    // rng order: tick#1 wander interval, wander target, arrival rest kind, arrival rest length, tick(13000) wander target
    const b = new Buddy({ rng: seq([0, 0.9, 0.9, 0, 0.9]), initialX: 0 })
    b.tick(0); b.tick(8000)
    b.arrived()                       // rest kind 0.9 -> looking, rest 0 -> 5000 ms -> restUntil 13000
    expect(b.view().state.activity).toBe('looking')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('idle')
    b.tick(12999)
    expect(b.view().state.activity).toBe('idle')
    b.tick(13000)
    expect(['walking', 'running']).toContain(b.view().state.activity)
  })
})

describe('Buddy commands', () => {
  it('goTo clamps, faces, runs when asked, and idles on arrival', () => {
    const b = new Buddy({ rng: seq([0]), initialX: 0.5 })
    b.tick(0)
    b.goTo(1.7, true)
    expect(b.view().state.targetX).toBe(1)
    expect(b.view().state.activity).toBe('running')
    expect(b.view().state.facing).toBe('right')
    b.arrived()
    expect(b.view().state.activity).toBe('idle')
    expect(b.view().state.x).toBe(1)
  })
  it('goTo without run picks walk or run by distance', () => {
    const b = new Buddy({ rng: seq([0]), initialX: 0.5 })
    b.tick(0)
    b.goTo(0.4)
    expect(b.view().state.activity).toBe('walking')
    expect(b.view().state.facing).toBe('left')
    b.arrived()
    b.goTo(0.0)
    expect(b.view().state.activity).toBe('running')
  })
  it('fires arrive listeners', () => {
    const b = new Buddy({ rng: seq([0]) })
    let n = 0
    b.onArrive(() => n++)
    b.tick(0); b.goTo(0.1); b.arrived()
    expect(n).toBe(1)
  })
})

describe('Buddy emotes and moods', () => {
  it('plays a one-shot emote from idle and returns to idle', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    expect(b.emote('confused')).toBe('started')
    expect(b.view().state.activity).toBe('emoting')
    expect(b.view().animation).toBe('emote_confused')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('idle')
  })
  it('returns to sitting after an emote started while sitting', () => {
    const b = new Buddy({ rng: seq([0, 0.9, 0.5, 0]), initialX: 0 })
    b.tick(0); b.tick(8000); b.arrived()
    expect(b.view().state.activity).toBe('sitting')
    b.emote('happy')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('sitting')
  })
  it('queues an emote behind movement', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.goTo(0.6)
    expect(b.emote('alarmed')).toBe('queued')
    expect(b.view().state.activity).toBe('walking')
    b.arrived()
    expect(b.view().animation).toBe('emote_alarmed')
  })
  it('an emote while projecting plays, returns to projecting on oneShotDone, and mood still applies', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.openPanel()
    expect(b.emote('happy')).toBe('started')
    expect(b.view().animation).toBe('emote_happy')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('projecting')
    expect(b.view().animation).toBe('project')
    b.setMood('happy')
    expect(b.view().state.mood).toBe('happy')
  })
  it('thinking replaces the project pose while projecting', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.openPanel()
    b.setMood('thinking')
    expect(b.view().animation).toBe('emote_thinking')
    b.setMood('calm')
    expect(b.view().animation).toBe('project')
  })
  it('thinking loops from idle until the mood changes', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.setMood('thinking')
    expect(b.view().animation).toBe('emote_thinking')
    expect(b.view().state.activity).toBe('emoting')
    b.setMood('calm')
    expect(b.view().state.activity).toBe('idle')
  })
  it('hop plays hop then fall', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.emote('hop')
    expect(b.view().animation).toBe('hop')
    b.oneShotDone()
    expect(b.view().animation).toBe('fall')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('idle')
  })
  it('emote(look) plays the look pose from idle and returns to idle', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.emote('look')
    expect(b.view().state.activity).toBe('looking')
    expect(b.view().animation).toBe('look')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('idle')
  })
  it('thinking set while walking becomes visible once he settles on arrival', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.goTo(0.6)
    expect(b.view().state.activity).toBe('walking')
    b.setMood('thinking')
    expect(b.view().state.activity).toBe('walking')   // still finishing the move
    b.arrived()
    expect(b.view().animation).toBe('emote_thinking')
  })
  it('emote(thinking) while running becomes visible on arrival and clears on calm', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.goTo(0.9, true)
    expect(b.view().state.activity).toBe('running')
    b.emote('thinking')
    b.arrived()
    expect(b.view().animation).toBe('emote_thinking')
    b.setMood('calm')
    expect(b.view().state.activity).toBe('idle')
  })
  it('emote(thinking) while asleep is a no-op', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.sleep()
    expect(b.view().state.asleep).toBe(true)
    b.emote('thinking')
    expect(b.view().state.mood).toBe('calm')
  })
})

describe('Buddy sleep', () => {
  it('sleeps after the quiet period and wakes on interaction', () => {
    const b = new Buddy({ rng: seq([0]), wanderIntervalMs: [1e9, 1e9] })   // never wanders in this test
    b.tick(0)
    b.tick(599999)
    expect(b.view().state.asleep).toBe(false)
    b.tick(600000)
    expect(b.view().state.asleep).toBe(true)
    expect(b.view().animation).toBe('sleep')
    b.tick(700000)
    expect(b.view().state.activity).toBe('sleeping')
    b.interact()
    expect(b.view().state.asleep).toBe(false)
    expect(b.view().state.activity).toBe('idle')
  })
  it('sleep() while the panel is open closes the panel and sleeps, wake() restores idle', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.openPanel(); b.sleep()
    expect(b.view().state.panelOpen).toBe(false)
    expect(b.view().state.asleep).toBe(true)
    b.wake()
    expect(b.view().state.activity).toBe('idle')
  })
  it('emits change events only when the view changes', () => {
    const b = new Buddy({ rng: seq([0]) })
    let n = 0
    b.onChange(() => n++)
    b.tick(0); b.tick(100); b.tick(200)
    expect(n).toBe(0)
    b.goTo(0.9)
    expect(n).toBe(1)
  })
  it('sleep() during a move finishes the move, fires onArrive, then sleeps', () => {
    const b = new Buddy({ rng: seq([0]) })
    let arrives = 0
    b.onArrive(() => arrives++)
    b.tick(0)
    b.goTo(0.9)
    expect(b.view().state.activity).toBe('running')
    b.sleep()
    expect(b.view().state.activity).toBe('running')
    expect(b.view().state.asleep).toBe(false)
    b.arrived()
    expect(arrives).toBe(1)
    expect(b.view().state.asleep).toBe(true)
    expect(b.view().animation).toBe('sleep')
    b.interact()
    expect(b.view().state.asleep).toBe(false)
  })
  it('opening the panel before arrival cancels a pending sleep', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.goTo(0.9)
    b.sleep()
    b.openPanel()
    b.arrived()
    expect(b.view().state.activity).toBe('projecting')
    expect(b.view().state.asleep).toBe(false)
  })
  it('a new command before arrival cancels a pending sleep, and a later sleep() still works', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0)
    b.goTo(0.9)
    b.sleep()
    b.goTo(0.2)
    b.arrived()
    expect(b.view().state.activity).toBe('idle')
    expect(b.view().state.asleep).toBe(false)
    b.sleep()
    expect(b.view().state.asleep).toBe(true)
  })
  it('an emote plays while projecting and returns to the project pose', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.openPanel()
    expect(b.emote('happy')).toBe('started')
    expect(b.view().animation).toBe('emote_happy')
    b.oneShotDone()
    expect(b.view().state.activity).toBe('projecting')
    expect(b.view().animation).toBe('project')
  })
  it('sleep while the panel is open closes the panel and sleeps', () => {
    const b = new Buddy({ rng: seq([0]) })
    b.tick(0); b.openPanel()
    b.sleep()
    expect(b.getState().panelOpen).toBe(false)
    expect(b.getState().asleep).toBe(true)
    expect(b.view().animation).toBe('sleep')
  })
})
